Feature/ab#246 enums
starwit/react-starwit pull request #15
Opened 2022-06-18 09:50 UTC by witchpou

added changes from reacthook-spring-template

2022-06-18 11:25 UTC, DerCed requested changes
Bitte noch,mal die == austauschen (wg Typensicherheit). Ansonsten passt das!

2022-06-18 11:25 UTC, DerCed commented on src/form/DefaultModifier.js
> +    return fieldType == "integer" ||
=== und nicht ==

2022-06-18 11:25 UTC, DerCed commented on src/form/DefaultModifier.js
> +                if (draft[field.name]?.id == -1 || draft[field.name] == "") {
=== und nicht ==

2022-06-18 11:25 UTC, DerCed commented on src/form/DefaultModifier.js
> +                if (draft[field.name] == "") {
See above

2022-06-18 11:25 UTC, DerCed commented on src/inputFields/validatedTextField/ValidatedTextField.jsx
> +        if (!!min && type != "string" && value < min) {
See above

2022-06-18 11:25 UTC, DerCed commented on src/inputFields/validatedTextField/ValidatedTextField.jsx
> +        if (!!max && type != "string" && value > max) {
See above

2022-06-20 13:11 UTC, witchpou commented on src/form/DefaultModifier.js
> +                if (draft[field.name]?.id == -1 || draft[field.name] == "") {
```suggestion
                if (draft[field.name]?.id === -1 || draft[field.name] === "") {
```

2022-06-20 13:12 UTC, witchpou commented on src/form/DefaultModifier.js
> +    return fieldType == "integer" ||
```suggestion
    return fieldType === "integer" ||
```

2022-06-20 13:13 UTC, witchpou commented on src/form/DefaultModifier.js
> +                if (draft[field.name] == "") {
```suggestion
                if (draft[field.name] === "") {
```

2022-06-20 13:13 UTC, witchpou commented on src/inputFields/validatedTextField/ValidatedTextField.jsx
> +        if (!!min && type != "string" && value < min) {
```suggestion
        if (!!min && type !== "string" && value < min) {
```

2022-06-20 15:37 UTC, merged